theme: jekyll-theme-midnight
title: Anamnesis
description: Anamnesis is a standalone tool that is used to modify certain clientside-only values and allow the user a greater degree of flexibility for making creative and interesting screenshots.
show_downloads: "True"
