blank_issues_enabled: false
contact_links:
  - name: XIV Tools Discord Server
    url: https://discord.gg/KvGJCCnG8t
    about: General help with the tool outside bug reports should be directed to the Community Support channel of the XIV Tools Discord server.
