name: Publish Anamnesis

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH
        utcOffset: "+10:00"
        
#    - name: Use current time
#      env:
#        TIME: "${{ steps.current-time.outputs.time }}"
#        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
#        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
#        YEAR: "${{ steps.current-time.outputs.year }}"
#        MONTH: "${{ steps.current-time.outputs.month }}"
#        DAY: "${{ steps.current-time.outputs.day }}"
#      run: echo $TIME $R_TIME $F_TIME $YEAR $MONTH $DAY
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Checkout Submodules
      uses: snickerbockers/submodules-init@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.x
   
    # Deploy Anamnesis
    - name: Deploy Anamnesis
      run: dotnet publish Anamnesis/Anamnesis.csproj /p:PublishProfile=".\Anamnesis\Properties\PublishProfiles\FolderProfile.pubxml"
      
    # Deploy Updater
    - name: Deploy Update Extractor
      run: dotnet publish UpdateExtractor/UpdateExtractor.csproj /p:PublishProfile=".\UpdateExtractor\Properties\PublishProfiles\FolderProfile.pubxml"

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        path: './publish/'
        exclusions: '*.pdb* *.xml*'
        
    - name: Run Changelog CI
      uses: saadmk11/changelog-ci@v0.8.0
      with:
        changelog_type: commit_message 
        # Optional, only required when you want more customization
        # e.g: group your changelog by labels with custom titles,
        # different version prefix, pull request title and version number regex etc.
        # config file can be in JSON or YAML format.
        #config_file: changelog-ci-config.json
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        name: ${{ steps.current-time.outputs.formattedTime }} (Beta)
        tag: v${{ steps.current-time.outputs.formattedTime }}-beta
        body_file: 'CHANGELOG.md'
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}

