name: Publish Anamnesis

on:
  workflow_dispatch:

jobs:

  build:

    #runs-on: windows-latest
    runs-on: ubuntu-latest

    steps:
    
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD
        
#    - name: Use current time
#      env:
#        TIME: "${{ steps.current-time.outputs.time }}"
#        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
#        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
#        YEAR: "${{ steps.current-time.outputs.year }}"
#        MONTH: "${{ steps.current-time.outputs.month }}"
#        DAY: "${{ steps.current-time.outputs.day }}"
#      run: echo $TIME $R_TIME $F_TIME $YEAR $MONTH $DAY
    
    - name: Generate Changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      id: Changelog
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Checkout Submodules
      uses: snickerbockers/submodules-init@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: 5.0.x
   
    - name: Deploy Anamnesis
      run: dotnet publish Anamnesis/Anamnesis.csproj /p:PublishProfile=".\Anamnesis\Properties\PublishProfiles\FolderProfile.pubxml"
      
    - name: Deploy Update Extractor
      run: dotnet publish UpdateExtractor/UpdateExtractor.csproj /p:PublishProfile=".\UpdateExtractor\Properties\PublishProfiles\FolderProfile.pubxml"

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        path: './publish/'
        exclusions: '*.pdb* *.xml*'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        name: ${{ steps.current-time.outputs.formattedTime }} (Beta)
        tag: v${{ steps.current-time.outputs.formattedTime }}-beta
        body: ${{ steps.Changelog.outputs.changelog }}
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}

