name: Publish Anamnesis

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Checkout submodules
      # You may pin to the exact commit or the version.
      # uses: textbook/git-checkout-submodule-action@0cb23c7e6a67085e1dc5e884920bd620f7b9c469
      uses: textbook/git-checkout-submodule-action@2.1.1

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore
    - name: Restore the application
      run: msbuild Anamnesis.sln /t:Restore /p:Configuration=Release
   
    # Deploy Anamnesis
    - name: Deploy Anamnesis
      run: msbuild Anamnesis/Anamnesis.csproj /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      
    # Deploy Updater
    - name: Deploy Update Extractor
      run: msbuild UpdateExtractor/UpdateExtractor.csproj /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
